[package]
name = "cfg"
version = "0.1.0"
authors = ["Anatolii <java1cprog@yandex.ru>"]
edition = "2018"

[dependencies]

[[bin]]
name = "my_new_crate"
path = "src/my_new_crate.rs"

[[bin]]
name = "cfg"
path = "src/cfg.rs"