[package]
name = "dev_dependencies"
version = "0.1.0"
authors = ["Anatolii <java1cprog@yandex.ru>"]
edition = "2018"

[dependencies]

# standard crate data is left out
[dev-dependencies]
pretty_assertions = "0.4.0"